### ISSUE TITLE
reference to a field

### ISSUE THREAD

**Issue by guiyomh** [guiyomh/charlatan#3]
Charlatan also allows you to directly reference to field using the `@name.property` notation.

```yaml
user:
    admin_1:
        first_name: 'William'
        last_name: 'Wallace'
        group_id: '@group_1.name'
    user_{1..10}:
        first_name: 'Bob <Current()>'
        last_name: 'The sponge'
        group_id: '@group_2.name'

group:
    group_1:
        name: admin
    group_2:
        name: reader
```
